create table if not exists email_analyses (
    id bigint generated by default as identity primary key,

    message_id text,
    sender text,
    recipient text,
    subject text,

    reply_to text,
    return_path text,

    raw_headers text,

    threat_score numeric default 0,

    classification text default 'unknown',

    created_at timestamptz default now()
);


create table if not exists email_indicators (
    id bigint generated by default as identity primary key,

    email_id bigint references email_analyses(id)
        on delete cascade,

    indicator_type text not null,

    value text not null,

    country text,
    region text,
    city text,

    latitude double precision,
    longitude double precision,

    isp text,
    asn text,
    organization text,

    reputation text,

    created_at timestamptz default now()
);


create table if not exists forensic_events (
    id bigint generated by default as identity primary key,

    email_id bigint references email_analyses(id)
        on delete cascade,

    event_type text not null,

    description text,

    event_time timestamptz default now(),

    metadata jsonb
);


create table if not exists attack_graph_nodes (
    id bigint generated by default as identity primary key,

    email_id bigint references email_analyses(id)
        on delete cascade,

    node_id text not null,

    node_type text not null,

    label text,

    metadata jsonb,

    created_at timestamptz default now()
);


create table if not exists attack_graph_edges (
    id bigint generated by default as identity primary key,

    email_id bigint references email_analyses(id)
        on delete cascade,

    source text not null,

    target text not null,

    relationship text not null,

    created_at timestamptz default now()
);


create index if not exists idx_email_indicators_value
on email_indicators(value);


create index if not exists idx_email_indicators_email
on email_indicators(email_id);


create index if not exists idx_forensic_events_email
on forensic_events(email_id);


create index if not exists idx_graph_nodes_email
on attack_graph_nodes(email_id);


create index if not exists idx_graph_edges_email
on attack_graph_edges(email_id);